### ISSUE TITLE
why do you use Vertx 

### ISSUE THREAD

**Issue by HoangNgo88** [zhaochuninhefei/web-performance-comparison#1]
Hi, Why do you use Vertx, are you using reactive programming, why dont you use Webflux in Spring. What is the difference between Vertx and Webflux when talking about Reactive Programming

**Comment by zhaochuninhefei** [comment]
Sorry for the late answer.
Using vertx is my friend aaavieri's suggestion, and the related code is also completed by him.
In fact, I don't rule out adding spring's webflux in the future to participate in the comparison.
As for the difference between vertx and webflux in reactive programming, I can only say that in my opinion, vertx, especially the vertx using kt, is more classic and easy to use. I can't answer the specifics very well, you can search for it yourself.
